import { getServerSession } from "next-auth";

import AuthProvider from "@/contexts/AuthContext";
import { AppProvider, DashboardLayout, Navigation } from "@toolpad/core";
import Image from "next/image";
import adminTheme from "@/theme/admin-theme";
import { AdminContentWrapper } from "@/components/admin/Content.style";

export const metadata = {
  title: "Admin - Ace My Exams",
  description: "Generated by create next app",
};

const NAVIGATION: Navigation = [
  {
    kind: "header",
    title: "Main items",
  },
  {
    segment: "admin/",
    title: "Dashboard",
  },
  {
    segment: "admin/resources",
    title: "Resources",
  },
];

export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <AuthProvider session={session}>
      <AppProvider
        session={session}
        navigation={NAVIGATION}
        theme={adminTheme}
        branding={{
          logo: <Image src="/logo.png" alt="Logo" width={32} height={32} />,
          title: "Ace My Exams",
        }}
        disableCollapsibleSidebar
      >
        <DashboardLayout>
          <AdminContentWrapper>{children}</AdminContentWrapper>
        </DashboardLayout>
      </AppProvider>
    </AuthProvider>
  );
}
